# Generated by Django 5.0.3 on 2024-03-31 19:15

import datetime
from django.db import migrations, models
from django.contrib.auth.models import Group


def create_user_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Doctor')
    Group.objects.get_or_create(name='Patient')



class Migration(migrations.Migration):


    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
