# Generated by Django 5.0.3 on 2024-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofuile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofuile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
