# Generated by Django 5.0.3 on 2024-04-01 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofuile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofuile',
            name='currently_hacking_on',
        ),
        migrations.RemoveField(
            model_name='userprofuile',
            name='currently_learning',
        ),
        migrations.RemoveField(
            model_name='userprofuile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofuile',
            name='skills_language',
        ),
        migrations.RemoveField(
            model_name='userprofuile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='userprofuile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofuile',
            name='work',
        ),
        migrations.AlterField(
            model_name='userprofuile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofuile',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofuile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofuile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofuile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
